### ISSUE TITLE
Merge with libxkbcommon?

### ISSUE THREAD

**Issue by whot** [whot/libxkbregistry#1]
Just filing a bug so I can cc @bluetech :)

Would you be happy with this in libxkbcommon?

**Comment by whot** [comment]
let's cc @svu as well so he's aware of the efforts here. Sergey: this is the first attempt at a library that wraps `evdev.xml` and similar so we don't rely on xml parsing in every user, which enables us to add things like `XInclude` to the xml files (and thus have user-specific XKB additions show up in the configuration panels).

**Comment by svu** [comment]
Thanks for the heads-up. Interesting idea!

**Comment by bluetech** [comment]
Hi @whot, let me explain the reason for my delay...

The purpose of this is to enable users to customize their keymaps. Our current plan for this is to have them adjust 3 different files:

- The XKB files -- custom XKB format.
- The rules file -- custom rules files format.
- The registry file -- custom XML format.

This is starting to look like the tower of Babel :) I don't think many users will be able to do it.

The idea is to get all of the relevant parties to switch over to libxkbregistry/xkbcommon-registry. But that makes me think, if we'll be going through all this effort, maybe we can come up with something better -- some way to simplify things?

At this point, I procrastinated, and I admittedly don't think I'm going to pursue this myself at this point. Given that, I am fine with proceeding to merge this into libxkbcommon.

Let me know how you'd like me to review -- a PR to the xkbcommon repo, review the code in this repo, or something else.

Sorry again for the delay!

**Comment by whot** [comment]
thanks for the comments! I'm aware of the need to stack all these pieces and how horribly they are as user-writable files, but unless somehow able to replace the whole stack in one go, there's not much we can do about that.

But let's assume we do replace everything with a more user-friendly file type, we'd still need two components: one to load the files for the compositors, one to list the files for the configuration tools. So either way we'd be looking at libxkbcommon + libxkbregistry.

Which means: if we get "everyone" to switch to those two, we can then change the underlying data format without other breakages. I for one look forward to our new JSON or YAML based XKB file overlords ;) The YAML is only half a joke, I think we could switch the existing format to base yaml and have it more readable and easier to parse. But that too is a lot of work for fairly little gain.

Anyway, i'll file PR to merge this into libxkbcommon and we can take it from there, thanks!

**Comment by hickford** [comment]
To avoid confusion, should this repo's README and description be updated to point to https://github.com/xkbcommon/libxkbcommon/ , where development continues?

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories

**Comment by whot** [comment]
@hickford done, thanks!

**Comment by whot** [comment]
libxkbregistry is part of libxkbcommon 1.0.0 and later
